name = "Breaking New Ground"
author = "Sir Bobbing"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bca4da350dd427d6f3a46f6d5cf15212d5b51b7d0a7a43968b0b61083b862cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = ["1.21.1"]
