name = "Breaking New Ground"
author = "Sir Bobbing"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "640352e06e5f07c7d50b626d10f427b0a292359d2f82aaa4fed22267496b6daa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
