// Visit the wiki for more info - https://kubejs.com/
console.info('Loaded JEI adjustments')

RecipeViewerEvents.removeEntries('item', event => {
    event.remove('scguns:pebbles')
    event.remove('scguns:niter_block')
    event.remove('copper_tools_armor_backport:copper_nugget')
    event.remove('spelunkery:copper_nugget')
    event.remove('tfmg:sulfur_dust')
    event.remove('tfmg:nitrate_dust')
    event.remove('malum:natural_quartz')
    event.remove('malum:natural_quartz_ore')
    event.remove('createbigcannons:cast_iron_nugget')
    event.remove('createbigcannons:cast_iron_ingot')
    event.remove('createbigcannons:cast_iron_block')
    event.remove('incubation:fried_egg')
    event.remove('createbigcannons:steel_ingot')
    event.remove('createbigcannons:steel_scrap')
    event.remove('createbigcannons:steel_block')
    event.remove('createbigcannons:gunpowder_pinch')

//Create Big Cannons Removals
    event.remove('createbigcannons:very_small_cast_mould')
    event.remove('createbigcannons:small_cast_mould')
    event.remove('createbigcannons:medium_cast_mould')
    event.remove('createbigcannons:large_cast_mould')
    event.remove('createbigcannons:very_large_cast_mould')
    event.remove('createbigcannons:cannon_end_cast_mould')
    event.remove('createbigcannons:sliding_breech_cast_mould')
    event.remove('createbigcannons:screw_breech_cast_mould')
    event.remove('createbigcannons:autocannon_breech_cast_mould')
    event.remove('createbigcannons:autocannon_recoil_spring_cast_mould')
    event.remove('createbigcannons:autocannon_barrel_cast_mould')

    event.remove('createbigcannons:unbored_very_small_steel_cannon_layer')
    event.remove('createbigcannons:unbored_very_small_nethersteel_cannon_layer')
    event.remove('createbigcannons:unbored_small_steel_cannon_layer')
    event.remove('createbigcannons:unbored_small_nethersteel_cannon_layer')
    event.remove('createbigcannons:unbored_medium_steel_cannon_layer')
    event.remove('createbigcannons:unbored_medium_nethersteel_cannon_layer')
    event.remove('createbigcannons:unbored_large_steel_cannon_layer')
    event.remove('createbigcannons:unbored_large_nethersteel_cannon_layer')
    event.remove('createbigcannons:unbored_very_large_steel_cannon_layer')
    event.remove('createbigcannons:unbored_very_large_nethersteel_cannon_layer')
    event.remove('createbigcannons:unbored_steel_screw_breech')
    event.remove('createbigcannons:unbored_nethersteel_screw_breech')
    event.remove('createbigcannons:unbored_steel_sliding_breech')

    event.remove('createbigcannons:unbored_cast_iron_cannon_barrel')
    event.remove('createbigcannons:unbored_cast_iron_cannon_chamber')
    event.remove('createbigcannons:unbored_cast_iron_sliding_breech')
    event.remove('createbigcannons:unbored_bronze_cannon_barrel')
    event.remove('createbigcannons:unbored_bronze_cannon_chamber')
    event.remove('createbigcannons:unbored_bronze_sliding_breech')

    event.remove('createbigcannons:very_small_steel_cannon_layer')
    event.remove('createbigcannons:very_small_nethersteel_cannon_layer')
    event.remove('createbigcannons:small_steel_cannon_layer')
    event.remove('createbigcannons:small_nethersteel_cannon_layer')
    event.remove('createbigcannons:medium_steel_cannon_layer')
    event.remove('createbigcannons:medium_nethersteel_cannon_layer')
    event.remove('createbigcannons:large_steel_cannon_layer')
    event.remove('createbigcannons:large_nethersteel_cannon_layer')
    event.remove('createbigcannons:very_large_steel_cannon_layer')
    event.remove('createbigcannons:very_large_nethersteel_cannon_layer')

    event.remove('createbigcannons:unbored_cast_iron_autocannon_breech')
    event.remove('createbigcannons:unbored_cast_iron_autocannon_recoil_spring')
    event.remove('createbigcannons:unbored_cast_iron_autocannon_barrel')
    event.remove('createbigcannons:unbored_bronze_autocannon_breech')
    event.remove('createbigcannons:unbored_bronze_autocannon_recoil_spring')
    event.remove('createbigcannons:unbored_bronze_autocannon_barrel')
    event.remove('createbigcannons:unbored_steel_autocannon_breech')
    event.remove('createbigcannons:unbored_steel_autocannon_recoil_spring')
    event.remove('createbigcannons:unbored_steel_autocannon_barrel')
    event.remove('createbigcannons:cannon_drill')
    event.remove('createbigcannons:casting_sand')
    event.remove('createbigcannons:cannon_builder')
    event.remove('createbigcannons:basin_foundry_lid')
    event.remove('createbigcannons:spring_wire')
    event.remove('createbigcannons:recoil_spring')
    event.remove('createbigcannons:incomplete_cast_iron_sliding_breech')
    event.remove('createbigcannons:incomplete_cast_iron_autocannon_breech')
    event.remove('createbigcannons:incomplete_cast_iron_autocannon_recoil_spring')
    event.remove('createbigcannons:incomplete_bronze_sliding_breech')
    event.remove('createbigcannons:incomplete_bronze_autocannon_breech')
    event.remove('createbigcannons:incomplete_bronze_autocannon_recoil_spring')
    event.remove('createbigcannons:incomplete_steel_sliding_breech')
    event.remove('createbigcannons:incomplete_steel_autocannon_breech')
    event.remove('createbigcannons:incomplete_steel_autocannon_recoil_spring')
    event.remove('createbigcannons:incomplete_steel_screw_breech')
    event.remove('createbigcannons:incomplete_nethersteel_screw_breech')

    event.remove('createbigcannons:nethersteel_screw_breech')
    event.remove('createbigcannons:thick_nethersteel_cannon_chamber')
    event.remove('createbigcannons:built_up_nethersteel_cannon_chamber')
    event.remove('createbigcannons:nethersteel_cannon_chamber')
    event.remove('createbigcannons:built_up_nethersteel_cannon_barrel')
    event.remove('createbigcannons:nethersteel_cannon_barrel')
    event.remove('createbigcannons:molten_nethersteel_bucket')
    event.remove('createbigcannons:nethersteel_screw_lock')
    event.remove('createbigcannons:nethersteel_nugget')
    event.remove('createbigcannons:nethersteel_ingot')
    event.remove('createbigcannons:nethersteel_block')
    event.remove('createbigcannons:molten_steel_bucket')

// DnD Missing Bolts
    event.remove('dndecor:lead_cross_bolt')
    event.remove('dndecor:lead_dash_bolt')
    event.remove('dndecor:lead_dot_bolt')
    event.remove('dndecor:lead_flat_bolt')
    event.remove('dndecor:aluminum_cross_bolt')
    event.remove('dndecor:aluminum_dash_bolt')
    event.remove('dndecor:aluminum_dot_bolt')
    event.remove('dndecor:aluminum_flat_bolt')
    event.remove('dndecor:nickel_cross_bolt')
    event.remove('dndecor:nickel_dash_bolt')
    event.remove('dndecor:nickel_dot_bolt')
    event.remove('dndecor:nickel_flat_bolt')
    event.remove('dndecor:steel_cross_bolt')
    event.remove('dndecor:steel_dash_bolt')
    event.remove('dndecor:steel_dot_bolt')
    event.remove('dndecor:steel_flat_bolt')
    event.remove('dndecor:cast_iron_cross_bolt')
    event.remove('dndecor:cast_iron_dash_bolt')
    event.remove('dndecor:cast_iron_dot_bolt')
    event.remove('dndecor:cast_iron_flat_bolt')

// Create Deco Removals
    event.remove('#createdeco:shipping_containers')
    event.remove('#createdeco:supports')

// Enchanted Books
    event.remove('minecraft:enchanted_book')
// Create Connected
    event.remove('create_connected:control_chip')
// Spelunkery
    event.remove('spelunkery:depth_gauge')
    event.remove('spelunkery:compression_blast_miner')
// CreatePropulsion
    event.remove('createpropulsion:platinum_block')
    event.remove('createpropulsion:platinum_casing')
    event.remove('createpropulsion:platinum_sheet')
    event.remove('createpropulsion:platinum_ingot')
    event.remove('createpropulsion:platinum_nugget')
    event.remove('createpropulsion:platinum_fluid_tank')
    event.remove('createpropulsion:raw_platinum')
    event.remove('createpropulsion:raw_platinum_block')
    event.remove('createpropulsion:cable_relay')
    event.remove('createpropulsion:cable')
    event.remove('createpropulsion:platinum_ore')
    event.remove('createpropulsion:deepslate_platinum_ore')
    event.remove('createpropulsion:pine_resin')
    event.remove('createpropulsion:turpentine_bucket')
// TFMG
    event.remove('tfmg:lithium_block')
    event.remove('tfmg:lithium_ingot')
    event.remove('tfmg:lithium_nugget')
    event.remove('tfmg:raw_lithium')
    event.remove('tfmg:raw_lithium_block')
    event.remove('tfmg:lithium_blade')
    event.remove('tfmg:lithium_torch')
    event.remove('tfmg:lithium_charge')
    event.remove('tfmg:lithium_ore')
    event.remove('tfmg:deepslate_lithium_ore')
    event.remove('tfmg:crushed_raw_lithium')

    // Malum
    event.remove('malum:block_of_brilliance')
    event.remove('malum:raw_brilliance')
    event.remove('malum:crushed_brilliance')
    event.remove('malum:brilliant_stone')
    event.remove('malum:brilliant_deepslate')
    event.remove('create:experience_nugget')

})
