#.
#Add enchantment IDs to this list to prevent them from being randomly enchanted.
FilteredEnchantments = ["minecraft:mending", "nova_structures:shulker_boss", "nova_structures:shulker_miniboss", "nova_structures:boss_behaviour", "nova_structures:photosynthesis"]
